### PR TITLE
Pull Request for inormalize-1.0.3

### PR DESCRIPTION
**Pull request by sandywang**
Dear Dr. Fonov,
I just updated codes based on Claude's ChangeLog.
Modified by Claude, * verbose = 0 in Spawn calls with stdout in a variable and release a new version 1.0.3.
I also added tags for 1.0.3 based on previous tag rule.

Best,
Xindi

### CODE REVIEW

**Comment by gdevenyi** [comment]
As with oobicpl, please open this PR against develop. Thanks.

**Comment by sandywang** [comment]
Dear Dr. Devenyi,
Because CIVET used a old version based on inormalize-1.0.2, is there a compromise that create a civet branch and update it from inormalize-1.0.2?

Best,
Xindi

**Comment by gdevenyi** [comment]
These changes are very minimal and should have no problems being applied onto the develop branch.

**Comment by gdevenyi** [comment]
Fixed base branch at #4

**Pull request closed without merging**
